### PR TITLE
Updated inline documentation

### PR DESCRIPTION
**Pull request by christian-krieg**

### CODE REVIEW

**Comment by cirosantilli** [comment]
Christian, can you split the last commit into a separate pull request? Let me know if you need any Git-fu help ;-)

**Comment by cirosantilli** [comment]
BTW, I changed the interface a bit on https://github.com/cirosantilli/vcdvcd/commit/ba56abd7119b7e28329c6608724c357153bc9025 (2.0.0 release), now you have to do `vcd.data['signalname'].tv` instead of `vcd.data['signalname']['tv']` to allow nice random access to signals: https://github.com/cirosantilli/vcdvcd/#api-usage

**Comment by christian-krieg** [comment]
Hey Ciro,

Sorry for my silence, was on vacation and took it very serious to really relax :)

> Christian, can you split the last commit into a separate pull request? Let me know if you need any Git-fu help ;-)

Sure, and I'll be happy to come back to your help offer ;)

Cheers,
Christian

**Comment by cirosantilli** [comment]
Hi there, hope you had a good vacation!

So the easiest thing here is to `git checkout master; git pull` to get the latest version on `master`, then create a new branch `git checkout -b amazing-feature`, and then `git cherry-pick` any missing commits.

Later on you might want to learn `git rebase --onto` for the day that there will be too many commits to cherry pick.

**Comment by christian-krieg** [comment]
Closing this PR now to keep things clean.

**Pull request closed without merging**
