### PR TITLE
Add robustness regarding VCD syntax

### PR DESCRIPTION
**Pull request by flaviens**
Hi,

We noticed that some tools may produce malformed VCD files.
This patch adds robustness so that vcdvcd works with more tools.

Kind regards,
Flavien

### CODE REVIEW

**Comment by cirosantilli** [comment]
Thanks :+1: 

Do you understand why the tool emits the `b1` line? What is is supposed to mean, or what triggers it? Since it is not assigning to anything.

**Comment by flaviens** [comment]
No, I do not know unfortunately. We ran a bunch of tests with an older
version of Verilator and we encountered a few lines like this.

**Comment by cirosantilli** [comment]
Merged at a6f1bc70a9e58a69a172c9749125841232a75e5b and made a relase :+1:

**Comment by cirosantilli** [comment]
I changed the print to a list to not pollute tests for example.

**Pull request closed without merging**
