### PR TITLE
Added support for single-line simulation command

### PR DESCRIPTION
**Pull request by christian-krieg**
* PulseView generates VCD files with value changes on the same line as the time stamp, separated by white-space
* Not sure if standard-compliant, but added support for it as GTKWave also supports it
* Added a test to the testbench

### CODE REVIEW

**Comment by DurandA** [comment]
I think it would be cleaner to only include commit c15abc6 in the PR.

**Comment by christian-krieg** [comment]
Hi Arnaud,

I totally agree, I also tried doing so, but it's unclear to me how to achieve it... github includes all the other commits as well, although my master branch (from which I forked the feature branch) is up to date with upstream master.

If obvious to you how to resolve this, I am more than open for advice (: Probably thr most straight-forward solution would be to do a fresh clone, apply changes, file new PR ...

Cheers,
Christian

**Comment by christian-krieg** [comment]
Did it following [this answer](https://stackoverflow.com/a/34027874) on StackOverflow.

I close this PR to keep things clean :)

Cheerio,
Christian

**Comment by DurandA** [comment]
Sorry for the late reply.

Another solution is to rebase:
```
git fetch upstream
git checkout feat/single-line-value-change
git rebase upstream/master
git push --force
```
You can also force push to the same branch instead of creating a new PR. It will replace all commits automatically.

**Pull request closed without merging**
