### PR TITLE
Package ready for PyPi

### PR DESCRIPTION
**Pull request by bmpenuelas**
Package the module for upload to PyPi

### CODE REVIEW

**Comment by cirosantilli** [comment]
Is it possible to keep `vcdcat` and `vcdvcd.py` on the toplevel directory? Feels better here since the repo is so small.

**Comment by cirosantilli** [comment]
Also it seems that currently `import vcdvcd` fails with:

````
ImportError: No module named vcdvcd
````

after a local install with:

````
python setup.py install --user
````

**Comment by bmpenuelas** [comment]
I'd stick to the standard directory structure no matter which size the package is.

`python setup.py install --user` is working using Python 3.6
image

`pip install -e . --user` works as well, and also `python -m pip install --index-url https://test.pypi.org/simple/ vcdvcd` which downloads it from the test PyPi.

Can you try this last method in a new virtual env?

**Comment by cirosantilli** [comment]
OK, it works on Python 3 but fails on Python 2 for me, either with or without virtualenv.

Do you reproduce? Is it possible to make it work for both? Ubuntu 18.10  phyton 3.6.5 and 2.7.15.

Python 3 is more important to me in general, but if it can work on both, even better.

**Comment by bmpenuelas** [comment]
Yes, sure, I can reproduce. That's due to the fact that Python 2 and 3 have different path handling capabilities. 

Give me a minute, I'll use a construct that works for both versions.

**Comment by bmpenuelas** [comment]
It should import fine now with both versions, I tested it in an AWS instance running Ubuntu and it's working with both python 2.7 and 3.5.

**Comment by cirosantilli** [comment]
OK thanks! I'll just review this tomorrow once more and then merge it.

**Comment by cirosantilli** [comment]
I have merged this as: 7c60be101c2cfea12598bce8a1c31415ca70b22f and uploaded to PyPi.

Some rationales for the changes from the PR:

- I'd rather keep as much on toplevel as possible, unless it adds a programmatic advantage. "flat is better than nested", less going in and out of directories :-)
- I'll keep the `.gitignore` more minimal and add stuff as we increase. I'd rather put all build into a single directory and ignore just that, but I was lazy to find out how for now for each tool.
- the vcdvcd/ directory remains, since I can't find out how to not have the directory! https://stackoverflow.com/questions/12461603/setting-up-setup-py-for-packaging-of-a-single-py-file-and-a-single-data-file-wi

**Pull request closed without merging**
